# Generated by Django 4.2.7 on 2023-11-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSpam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
