# Generated by Django 4.2.7 on 2023-11-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecaller_app', '0002_globalspam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
